using JuMP

include("fullspace.jl")

m = generate_fullspace()
stat = solve(m)


include("secondCNF.jl")

cnf = generate_secondCNF()
stat = solve(cnf)


include("secondDNF.jl")
dnf = generate_secondDNF()
stat = solve(dnf)

println("objective value")
println(getobjectivevalue(m))
println("solver status")
println(stat)
println("First stage varialbes")
println("p1")
println(getvalue(getindex(m, :p1)))
println("p2:")
println(getvalue(getindex(m, :p2)))
println("x1")
println(getvalue(getindex(m, :x1)))
println("x2:")
println(getvalue(getindex(m, :x2)))
println("\nSecond stage varialbes")
println("y1")
println(getvalue(getindex(m, :y1)))
println("y2:")
println(getvalue(getindex(m, :y2)))
println("q1")
println(getvalue(getindex(m, :q1)))
println("q2:")
println(getvalue(getindex(m, :q2)))
println("δ:")
println(getvalue(getindex(m, :δ)))
println("\n\n\n")
println("objective value")
println(getobjectivevalue(cnf))
println("solver status")
println(stat)
println("First stage varialbes")
println("p1")
println(getvalue(getindex(cnf, :p1)))
println("p2:")
println(getvalue(getindex(cnf, :p2)))
println("x1")
println(getvalue(getindex(cnf, :x1)))
println("x2:")
println(getvalue(getindex(cnf, :x2)))
println("\nSecond stage varialbes")
println("y1")
println(getvalue(getindex(cnf, :y1)))
println("y2:")
println(getvalue(getindex(cnf, :y2)))
println("q1")
println(getvalue(getindex(cnf, :q1)))
println("q2:")
println(getvalue(getindex(cnf, :q2)))
println("δ:")
println(getvalue(getindex(cnf, :δ)))
println("\n\n\n")
println("objective value")
println(getobjectivevalue(dnf))
println("solver status")
println(stat)
println("First stage varialbes")
println("p1")
println(getvalue(getindex(dnf, :p1)))
println("p2:")
println(getvalue(getindex(dnf, :p2)))
println("x1")
println(getvalue(getindex(dnf, :x1)))
println("x2:")
println(getvalue(getindex(dnf, :x2)))
println("\nSecond stage varialbes")
println("y1")
println(getvalue(getindex(dnf, :y1)))
println("y2:")
println(getvalue(getindex(dnf, :y2)))
println("q1")
println(getvalue(getindex(dnf, :q1)))
println("q2:")
println(getvalue(getindex(dnf, :q2)))
println("δ:")
println(getvalue(getindex(dnf, :δ)))