include("input.jl")
include("fullspace.jl")
m = generate_fullspace()
solve(m)
println(getobjectivevalue(m))
println(getvalue(getindex(m, :p1)))
println(getvalue(getindex(m, :p2)))
println(getvalue(getindex(m, :x1)))
println(getvalue(getindex(m, :x2)))